// This file was generated by Prisma 7 and is not used with Prisma 5.
// It is kept for reference only.
// @ts-nocheck
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
